// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Restaurante.Migrations;

#nullable disable

namespace Restaurante.Migrations.Migrations
{
    [DbContext(typeof(RestauranteContext))]
    [Migration("20241112012045_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.35")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Restaurante.Models.DetallePedido", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("id");

                    b.Property<double>("Cantidad")
                        .HasColumnType("float")
                        .HasColumnName("cantidad");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2024, 11, 12, 1, 20, 44, 795, DateTimeKind.Utc).AddTicks(3541))
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_at");

                    b.Property<string>("PedidoId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProductoId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("SubTotal")
                        .HasColumnType("float")
                        .HasColumnName("subtotal");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId");

                    b.HasIndex("ProductoId");

                    b.ToTable("detalle_pedido");
                });

            modelBuilder.Entity("Restaurante.Models.Domicilio", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Calle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("calle");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2024, 11, 12, 1, 20, 44, 794, DateTimeKind.Utc).AddTicks(7966))
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Localidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("localidad");

                    b.Property<int>("Numero")
                        .HasColumnType("int")
                        .HasColumnName("numero");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("domicilios");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Calle = "Espejo",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Localidad = "Capital",
                            Numero = 450
                        },
                        new
                        {
                            Id = 2L,
                            Calle = "Patricias Mendocinas",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Localidad = "Capital",
                            Numero = 890
                        },
                        new
                        {
                            Id = 3L,
                            Calle = "España",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Localidad = "Capital",
                            Numero = 305
                        },
                        new
                        {
                            Id = 4L,
                            Calle = "Godoy Cruz",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Localidad = "Capital",
                            Numero = 210
                        },
                        new
                        {
                            Id = 5L,
                            Calle = "Avenida San Martín",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Localidad = "Capital",
                            Numero = 1200
                        });
                });

            modelBuilder.Entity("Restaurante.Models.Ingrediente", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2024, 11, 12, 1, 20, 44, 795, DateTimeKind.Utc).AddTicks(1750))
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_at");

                    b.Property<string>("ImagenUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("imagen");

                    b.Property<double>("PrecioCompra")
                        .HasColumnType("float")
                        .HasColumnName("precio_compra");

                    b.Property<double>("PrecioVenta")
                        .HasColumnType("float")
                        .HasColumnName("precio_venta");

                    b.Property<double>("StockActual")
                        .HasColumnType("float")
                        .HasColumnName("stock_actual");

                    b.Property<double>("StockAlerta")
                        .HasColumnType("float")
                        .HasColumnName("stock_alerta");

                    b.Property<string>("Unidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("unidad");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("ingredientes");
                });

            modelBuilder.Entity("Restaurante.Models.Pedido", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2024, 11, 12, 1, 20, 44, 795, DateTimeKind.Utc).AddTicks(4157))
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("pedidos");
                });

            modelBuilder.Entity("Restaurante.Models.Persona", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("apellido");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2024, 11, 12, 1, 20, 44, 794, DateTimeKind.Utc).AddTicks(9490))
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_at");

                    b.Property<long?>("DomicilioId")
                        .HasColumnType("bigint")
                        .HasColumnName("domicilio_id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nombre");

                    b.Property<long?>("TelefonoId")
                        .HasColumnType("bigint")
                        .HasColumnName("telefono_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("DomicilioId");

                    b.HasIndex("TelefonoId");

                    b.ToTable("personas");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Apellido = "Fernández",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DomicilioId = 1L,
                            Nombre = "Lucía",
                            TelefonoId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            Apellido = "González",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DomicilioId = 2L,
                            Nombre = "Mateo",
                            TelefonoId = 2L
                        },
                        new
                        {
                            Id = 3L,
                            Apellido = "López",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DomicilioId = 3L,
                            Nombre = "Sofía",
                            TelefonoId = 3L
                        },
                        new
                        {
                            Id = 4L,
                            Apellido = "Rodríguez",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DomicilioId = 4L,
                            Nombre = "Tomás",
                            TelefonoId = 4L
                        },
                        new
                        {
                            Id = 5L,
                            Apellido = "Gallardo",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DomicilioId = 5L,
                            Nombre = "Ariel",
                            TelefonoId = 5L
                        });
                });

            modelBuilder.Entity("Restaurante.Models.Producto", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2024, 11, 12, 1, 20, 44, 795, DateTimeKind.Utc).AddTicks(2997))
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_at");

                    b.Property<string>("ImagenUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("imagen");

                    b.Property<double>("PrecioCompra")
                        .HasColumnType("float")
                        .HasColumnName("precio_compra");

                    b.Property<double>("PrecioVenta")
                        .HasColumnType("float")
                        .HasColumnName("precio_venta");

                    b.Property<double>("StockActual")
                        .HasColumnType("float")
                        .HasColumnName("stock_actual");

                    b.Property<double>("StockAlerta")
                        .HasColumnType("float")
                        .HasColumnName("stock_alerta");

                    b.Property<string>("Unidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("unidad");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("productos");
                });

            modelBuilder.Entity("Restaurante.Models.ProductoIngrediente", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("id");

                    b.Property<double>("Cantidad")
                        .HasColumnType("float")
                        .HasColumnName("cantidad");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2024, 11, 12, 1, 20, 44, 795, DateTimeKind.Utc).AddTicks(2359))
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_at");

                    b.Property<string>("IngredienteId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("ingrediente_id");

                    b.Property<string>("ProductoId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("producto_id");

                    b.Property<string>("Unidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("unidad");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("IngredienteId");

                    b.HasIndex("ProductoId");

                    b.ToTable("producto_ingrediente");
                });

            modelBuilder.Entity("Restaurante.Models.Rol", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2024, 11, 12, 1, 20, 44, 794, DateTimeKind.Utc).AddTicks(6766))
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("descripcion");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Descripcion")
                        .IsUnique();

                    b.ToTable("roles");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descripcion = "Cliente"
                        },
                        new
                        {
                            Id = 2L,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descripcion = "Delivery"
                        },
                        new
                        {
                            Id = 3L,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descripcion = "Recepcionista"
                        },
                        new
                        {
                            Id = 4L,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descripcion = "Cocinero"
                        },
                        new
                        {
                            Id = 5L,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descripcion = "Administrador"
                        });
                });

            modelBuilder.Entity("Restaurante.Models.Telefono", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<int>("CodigoArea")
                        .HasColumnType("int")
                        .HasColumnName("codigo_area");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2024, 11, 12, 1, 20, 44, 794, DateTimeKind.Utc).AddTicks(8766))
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_at");

                    b.Property<decimal>("Numero")
                        .HasColumnType("decimal(20,0)")
                        .HasColumnName("numero");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("telefonos");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CodigoArea = 261,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Numero = 1235670m
                        },
                        new
                        {
                            Id = 2L,
                            CodigoArea = 261,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Numero = 9875420m
                        },
                        new
                        {
                            Id = 3L,
                            CodigoArea = 261,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Numero = 6548320m
                        },
                        new
                        {
                            Id = 4L,
                            CodigoArea = 261,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Numero = 9852010m
                        },
                        new
                        {
                            Id = 5L,
                            CodigoArea = 261,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Numero = 7116429m
                        });
                });

            modelBuilder.Entity("Restaurante.Models.Usuario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2024, 11, 12, 1, 20, 44, 795, DateTimeKind.Utc).AddTicks(249))
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("email");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("password");

                    b.Property<long?>("PersonaId")
                        .IsRequired()
                        .HasColumnType("bigint")
                        .HasColumnName("persona_id");

                    b.Property<long?>("RolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("rol_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PersonaId");

                    b.HasIndex("RolId");

                    b.ToTable("usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "cliente@restaurante.com",
                            Password = "$2a$11$Md2.ACBRv9JENhYZo/OsdOPem7J1VyKhjCQK4/xjthVy7Hb/kxd0i",
                            PersonaId = 1L,
                            RolId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "delivery@restaurante.com",
                            Password = "$2a$11$Md2.ACBRv9JENhYZo/OsdOPem7J1VyKhjCQK4/xjthVy7Hb/kxd0i",
                            PersonaId = 2L,
                            RolId = 2L
                        },
                        new
                        {
                            Id = 3L,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "recepcionista@restaurante.com",
                            Password = "$2a$11$Md2.ACBRv9JENhYZo/OsdOPem7J1VyKhjCQK4/xjthVy7Hb/kxd0i",
                            PersonaId = 3L,
                            RolId = 3L
                        },
                        new
                        {
                            Id = 4L,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "cocinero@restaurante.com",
                            Password = "$2a$11$Md2.ACBRv9JENhYZo/OsdOPem7J1VyKhjCQK4/xjthVy7Hb/kxd0i",
                            PersonaId = 4L,
                            RolId = 4L
                        },
                        new
                        {
                            Id = 5L,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "administrador@restaurante.com",
                            Password = "$2a$11$Md2.ACBRv9JENhYZo/OsdOPem7J1VyKhjCQK4/xjthVy7Hb/kxd0i",
                            PersonaId = 5L,
                            RolId = 5L
                        });
                });

            modelBuilder.Entity("Restaurante.Models.DetallePedido", b =>
                {
                    b.HasOne("Restaurante.Models.Pedido", null)
                        .WithMany("Detalles")
                        .HasForeignKey("PedidoId");

                    b.HasOne("Restaurante.Models.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("Restaurante.Models.Persona", b =>
                {
                    b.HasOne("Restaurante.Models.Domicilio", "Domicilio")
                        .WithMany()
                        .HasForeignKey("DomicilioId");

                    b.HasOne("Restaurante.Models.Telefono", "Telefono")
                        .WithMany()
                        .HasForeignKey("TelefonoId");

                    b.Navigation("Domicilio");

                    b.Navigation("Telefono");
                });

            modelBuilder.Entity("Restaurante.Models.ProductoIngrediente", b =>
                {
                    b.HasOne("Restaurante.Models.Ingrediente", "Ingrediente")
                        .WithMany()
                        .HasForeignKey("IngredienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Restaurante.Models.Producto", "Producto")
                        .WithMany("Ingredientes")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingrediente");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("Restaurante.Models.Usuario", b =>
                {
                    b.HasOne("Restaurante.Models.Persona", "Persona")
                        .WithMany()
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Restaurante.Models.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("RolId");

                    b.Navigation("Persona");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("Restaurante.Models.Pedido", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("Restaurante.Models.Producto", b =>
                {
                    b.Navigation("Ingredientes");
                });
#pragma warning restore 612, 618
        }
    }
}
