<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="6.0.36" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Restaurante.Infraestructure\Restaurante.Infraestructure.csproj" />
    <ProjectReference Include="..\Restaurante.Services.Interfaces\Restaurante.Services.Interfaces.csproj" />
    <ProjectReference Include="..\Restaurante.Services\Restaurante.Services.csproj" />
  </ItemGroup>

</Project>
